# Find School's County
PREFIX ont: <http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wiki: <http://wiki/>

SELECT ?okrug
WHERE {
  <http://jjzmaj.edu.rs> ont:isLocated ?adresa .
  ?adresa ont:isPartOf ?grad .
  ?grad ont:isPartOf ?opstina .
  ?opstina ont:isPartOf ?okrug .
}

# Finds all schools in a county

PREFIX ont: <http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wiki: <http://wiki/>

SELECT ?school {
  ?school rdf:type ?any_school.
  ?any_school rdfs:subClassOf ?highSchool .
  ?highSchool rdfs:subClassOf ont:School .
  ?school ont:isLocated ?adresa .
  ?adresa ont:isPartOf ?grad .
  ?grad ont:isPartOf ?opstina .
  ?opstina ont:isPartOf wiki:JBacki .
}