# Example data insertion
PREFIX ont: <http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wiki: <http://wiki/>

INSERT DATA
{
  wiki:JBacki rdf:type ont:County ;
  ont:name "Juznobački okrug" .
};

INSERT DATA
{
  wiki:SevernoBacki rdf:type ont:County ;
  ont:name "Severnobački  okrug" .
};

INSERT DATA
{
  wiki:Sremski rdf:type ont:County ;
  ont:name "Sremski okrug" .
};

INSERT DATA
{
  wiki:NoviSad rdf:type ont:Municipality ;
  ont:name "Novi Sad" ;
  ont:isPartOf wiki:JBacki .
};

INSERT DATA
{
  wiki:Becej rdf:type ont:Municipality ;
  ont:name "Becej" ;
  ont:isPartOf wiki:JBacki .
};

INSERT DATA
{
  wiki:BackaTopola rdf:type ont:Municipality ;
  ont:name "Bačka Topola" ;
  ont:isPartOf wiki:SevernoBacki .
};

INSERT DATA
{
  wiki:OpstinaSremskaMitrovica rdf:type ont:Municipality ;
  ont:name "Opština Sremska Mitrovica" ;
  ont:isPartOf wiki:Sremski .
};

INSERT DATA
{
  wiki:CityOfNoviSad rdf:type ont:City ;
  ont:name "Novi Sad" ;
  ont:isPartOf wiki:NoviSad .
};

INSERT DATA
{
  wiki:CityOfBecej rdf:type ont:City ;
  ont:name "Becej" ;
  ont:isPartOf wiki:Becej .
};

INSERT DATA
{
  wiki:CityOfSremskaMitrovica rdf:type ont:City ;
  ont:name "Sremska Mitrocica" ;
  ont:isPartOf wiki:OpstinaSremskaMitrovica .
};

INSERT DATA
{
  wiki:CityOfBackaTopola rdf:type ont:City ;
  ont:name "Bačka topola" ;
  ont:isPartOf wiki:BackaTopola .
};

#Languages

INSERT DATA
{
  wiki:Serbian rdf:type ont:TeachingLanguage ;
  ont:name "Srpski" .
};

INSERT DATA
{
  wiki:Hungarian rdf:type ont:TeachingLanguage ;
  ont:name "Madjarski" .
};

INSERT DATA
{
  wiki:Slovak rdf:type ont:TeachingLanguage ;
  ont:name "Slovacki" .
};

INSERT DATA
{
  wiki:English rdf:type ont:ForeignLanguage ;
  rdf:type ont:TeachingLanguage ;
  ont:name "Engleski" .
};

INSERT DATA
{
  wiki:German rdf:type ont:ForeignLanguage ;
  rdf:type ont:TeachingLanguage ;
  ont:name "Nemacki" .
};

INSERT DATA
{
  wiki:French rdf:type ont:ForeignLanguage ;
  rdf:type ont:TeachingLanguage ;
  ont:name "Francuski" .
};

INSERT DATA
{
  wiki:Spanish rdf:type ont:ForeignLanguage ;
  ont:name "Spanski" .
};

INSERT DATA
{
  wiki:Russian rdf:type ont:ForeignLanguage ;
  ont:name "Ruski" .
};

# Gimnazija Jovan Jovanovic Zmaj

INSERT DATA
{
  wiki:Address1 rdf:type ont:Address ;
  ont:name "Zlatne Grede 4" ;
  ont:isPartOf wiki:CityOfNoviSad .
};

INSERT DATA
{
  <http://jjzmaj.edu.rs> rdf:type ont:GrammarSchool ;
  ont:name "Jovan Jovanovic Zmaj" ;
  ont:isLocated wiki:Address1 ;
  ont:numberOfTeacherSSS 0.0 ;
  ont:numberOfTeacherHigherSS 0.0 ;
  ont:numberOfTeacherHighSS 87.51 ;
  ont:hasTeachingLanguage wiki:Serbian ;
  ont:hasForeignLanguage wiki:English ;
  ont:hasForeignLanguage wiki:German ;
  ont:hasForeignLanguage wiki:French ;
  ont:hasForeignLanguage wiki:Spanish ;
  ont:hasTeachingLanguage wiki:English ;
  ont:hasTeachingLanguage wiki:German ;
  ont:hasTeachingLanguage wiki:French ;
  ont:numberOfShifts 3.
};

# Gimnazija Svetozar Markovic

INSERT DATA
{
  wiki:Address2 rdf:type ont:Address ;
  ont:name "Njegoseva 22" ;
  ont:isPartOf wiki:CityOfNoviSad .
};

INSERT DATA
{
  <http://www.s-markovic.edu.rs/> rdf:type ont:GrammarSchool ;
  ont:name "Svetozar Markovic" ;
  ont:isLocated wiki:Address2 ;
  ont:numberOfTeacherSSS 0.0 ;
  ont:numberOfTeacherHigherSS 0.1 ;
  ont:numberOfTeacherHighSS 64.27 ;
  ont:hasTeachingLanguage wiki:Serbian ;
  ont:hasTeachingLanguage wiki:Hungarian ;
  ont:hasForeignLanguage wiki:English ;
  ont:hasForeignLanguage wiki:German ;
  ont:hasForeignLanguage wiki:French ;
  ont:numberOfShifts 2.
};

#ETS Mihajlo Pupin

INSERT DATA
{
  wiki:Address3 rdf:type ont:Address ;
  ont:name "Futoska 17" ;
  ont:isPartOf wiki:CityOfNoviSad .
};

INSERT DATA
{
  <http://www.s-markovic.edu.rs/> rdf:type ont:VocationalSchool ;
  ont:name "Mihajlo Pupin" ;
  ont:isLocated wiki:Address3 ;
  ont:numberOfTeacherSSS 0.0 ;
  ont:numberOfTeacherHigherSS 2.0 ;
  ont:numberOfTeacherHighSS 154.98 ;
  ont:hasTeachingLanguage wiki:Serbian ;
  ont:hasTeachingLanguage wiki:Hungarian ;
  ont:hasForeignLanguage wiki:English ;
  ont:hasForeignLanguage wiki:German ;
  ont:hasForeignLanguage wiki:Russian ;
  ont:numberOfShifts 2.

};

INSERT DATA
{
  wiki:Address3 rdf:type ont:Address ;
  ont:name "Urosa Predica 1" ;
  ont:isPartOf wiki:CityOfBecej .
};

INSERT DATA
{
  <http://tsbecej.edu.rs/> rdf:type ont:VocationalSchool ;
  ont:name "Tehnicka skola" ;
  ont:isLocated wiki:Address3 ;
  ont:numberOfTeacherSSS 4.4 ;
  ont:numberOfTeacherHigherSS 1.19 ;
  ont:numberOfTeacherHighSS 31.10 ;
  ont:hasTeachingLanguage wiki:Serbian ;
  ont:hasTeachingLanguage wiki:Hungarian ;
  ont:numberOfShifts 1.
};

# Mitrovačka gimnazija

INSERT DATA
{
  wiki:Address4 rdf:type ont:Address ;
  ont:name "Светог Саве 2" ;
  ont:isPartOf wiki:CityOfSremskaMitrovica .
};

INSERT DATA
{
  wiki:CityOfSremskaMitrovica ont:isPartOf wiki:Sremski .
};

INSERT DATA
{
  <http://www.gimnazijasm.edu.rs/> rdf:type ont:GrammarSchool ;
  ont:name "Mitrovačka gimnazija" ;
  ont:schoolType 5 ;
  ont:isLocated wiki:Address4 .
};

# Agricultural school Bačka Topola

INSERT DATA
{
  wiki:Address5 rdf:type ont:Adress ;
  ont:name "Poljoprivredna škola Bačka Topola" ;
  ont:isPartOf wiki:CityOfBackaTopola .
};

INSERT DATA
{
  wiki:CityOfBackaTopola ont:isPartOf wiki:SevernoBacki .
};

INSERT DATA
{
  <http://poljoskola.edu.rs> rdf:type ont:VocationalSchool ;
  ont:name "Poljoprivredna škola Bačka topola" ;
  ont:schoolType 5 ;
  ont:isLocated wiki:Address5 .
};
